### ISSUE TITLE
EcmaError: ScriptException: ReferenceError:"Promise" is not defined

### ISSUE THREAD

**Issue by DeborahAnn032** [HtmlUnit/htmlunit-android#14]
I am using HtmlUnit on my android project:

        implementation 'net.sourceforge.htmlunit:htmlunit:2.15'

I am simply try to get a webpage:

    private final static String LOGIN_URL = "https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin";
        private final static WebClient webClient = new WebClient(BrowserVersion.FIREFOX.24);
        java.util.logging.Logger.getLogger("com.gargoylesoftware.htmlunit").setLevel(java.util.logging.Level.OFF);
        java.util.logging.Logger.getLogger("org.apache.http").setLevel(java.util.logging.Level.OFF);
        final HtmlPage page = webClient.getPage(LOGIN_URL);

However this is the exception I get at runtime:

  

        2022-12-09 20:31:43.460 20894-24897/com.test.xxx I/System.out: ======= EXCEPTION START ========
    2022-12-09 20:31:43.460 20894-24897/com.test.xxx I/System.out: EcmaError: lineNumber=[39] column=[0] lineSource=[<no source>] name=[ReferenceError] sourceName=[script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994)] message=[ReferenceError: "Promise" is not defined. (script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994)#39)]
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out: com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "Promise" is not defined. (script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994)#39)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:705)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:620)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:591)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:566)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptIfPossible(HtmlPage.java:975)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded(HtmlScript.java:349)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:274)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:288)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:741)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source:35)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:701)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at org.apache.xerces.parsers.XMLParser.parse(Unknown Source:5)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:965)
    2022-12-09 20:31:43.461 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:247)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:193)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:468)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:342)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:407)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:392)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.test.xxx.thread.PTCThread.run(PTCThread.java:58)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out: Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: ReferenceError: "Promise" is not defined. (script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994)#39)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3629)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3613)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3683)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1754)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.name(ScriptRuntime.java:1695)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1622)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:411)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3057)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:582)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:690)
    2022-12-09 20:31:43.462 20894-24897/com.test.xxx I/System.out: 	... 32 more
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out: Enclosed exception: 
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out: net.sourceforge.htmlunit.corejs.javascript.EcmaError: ReferenceError: "Promise" is not defined. (script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994)#39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3629)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3613)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:3683)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.nameOrFunction(ScriptRuntime.java:1754)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.name(ScriptRuntime.java:1695)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1622)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at script(script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994):39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at script(script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994):39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at script(script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994):39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at script(script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994):39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at script(script in https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin from (38, 32) to (39, 52994):39)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:798)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:105)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:411)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:309)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3057)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.exec(InterpretedFunction.java:115)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:582)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:690)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:620)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:513)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:591)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:566)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptIfPossible(HtmlPage.java:975)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.executeInlineScriptIfNeeded(HtmlScript.java:349)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:409)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript$3.execute(HtmlScript.java:274)
    2022-12-09 20:31:43.463 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:288)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:741)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source:35)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:701)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1170)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1072)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.filters.DefaultFilter.endElement(DefaultFilter.java:206)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.filters.NamespaceBinder.endElement(NamespaceBinder.java:330)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3126)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2093)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLScanner.scanDocument(HTMLScanner.java:920)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:499)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.cyberneko.html.HTMLConfiguration.parse(HTMLConfiguration.java:452)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at org.apache.xerces.parsers.XMLParser.parse(Unknown Source:5)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.parse(HTMLParser.java:965)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser.parse(HTMLParser.java:247)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.html.HTMLParser.parseHtml(HTMLParser.java:193)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.DefaultPageCreator.createHtmlPage(DefaultPageCreator.java:268)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.DefaultPageCreator.createPage(DefaultPageCreator.java:156)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:468)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:342)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:407)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:392)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out:     at com.test.xxx.thread.PTCThread.run(PTCThread.java:58)
    2022-12-09 20:31:43.464 20894-24897/com.test.xxx I/System.out: ======= EXCEPTION END ========

I have no idea what `Promise` not being defined means, it sure looks like an error during the parsing of the script. By the way, I am using an old version because with this one my app worked just fine until a few months ago.

**Comment by rbri** [comment]
Hi @DeborahAnn032 

HtmlUnit 2.12 is really outdated (from Mar 6, 2013) and i fear there was no promise support at that time.
And because i do all this in my spare time i can not really support this old version.

Please switch to the latest htmlunit (and because you are on android, please use htmlunit-adroid https://github.com/HtmlUnit/htmlunit-android)

Hope that helps....
