### ISSUE TITLE
java.lang.ExceptionInInitializerError: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl"

### ISSUE THREAD

**Issue by PolyakovVladislav** [HtmlUnit/htmlunit-android#17]
Hello. Facing a crash on atempt to create new client via dagger provider.
**Edit**: App is crashing even without dagger
**Code:**
```
@Module
@InstallIn(SingletonComponent::class)
object SteamApiModule {

    @Singleton
    @Provides
    fun provideHtmlUnit() =
        WebClient(BrowserVersion.CHROME)
}
```

**Crash log:**
```
java.lang.ExceptionInInitializerError
                 	at ua.dualbot.impl.di.SteamApiModule.provideHtmlUnit(SteamApiModule.kt:22)
                 	at ua.dualbot.impl.di.SteamApiModule_ProvideHtmlUnitFactory.provideHtmlUnit(SteamApiModule_ProvideHtmlUnitFactory.java:31)
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApp_HiltComponents_SingletonC.java:554)
                 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApp_HiltComponents_SingletonC.java:551)
                 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity2(DaggerMainApp_HiltComponents_SingletonC.java:400)
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity(DaggerMainApp_HiltComponents_SingletonC.java:395)
                 	at ua.dualbot.steammarketbot.Hilt_MainActivity.inject(Hilt_MainActivity.java:67)
                 	at ua.dualbot.steammarketbot.Hilt_MainActivity$1.onContextAvailable(Hilt_MainActivity.java:38)
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362)
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217)
                 	at ua.dualbot.steammarketbot.MainActivity.onCreate(MainActivity.kt:16)
                 	at android.app.Activity.performCreate(Activity.java:8000)
                 	at android.app.Activity.performCreate(Activity.java:7984)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loop(Looper.java:223)
                 	at android.app.ActivityThread.main(ActivityThread.java:7656)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
                 Caused by: org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/lib/x86, /system/lib, /system_ext/lib]] (Caused by java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/lib/x86, /system/lib, /system_ext/lib]])
                 	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158)
                 	at org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960)
                 	at java.security.AccessController.doPrivileged(AccessController.java:43)
                 	at org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957)
                 	at org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624)
                 	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655)
                 	at com.gargoylesoftware.htmlunit.WebClient.<clinit>(WebClient.java:162)
                 	at ua.dualbot.impl.di.SteamApiModule.provideHtmlUnit(SteamApiModule.kt:22) 
                 	at ua.dualbot.impl.di.SteamApiModule_ProvideHtmlUnitFactory.provideHtmlUnit(SteamApiModule_ProvideHtmlUnitFactory.java:31) 
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApp_HiltComponents_SingletonC.java:554) 
                 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$SingletonCImpl$SwitchingProvider.get(DaggerMainApp_HiltComponents_SingletonC.java:551) 
                 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47) 
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity2(DaggerMainApp_HiltComponents_SingletonC.java:400) 
                 	at ua.dualbot.steammarketbot.DaggerMainApp_HiltComponents_SingletonC$ActivityCImpl.injectMainActivity(DaggerMainApp_HiltComponents_SingletonC.java:395) 
                 	at ua.dualbot.steammarketbot.Hilt_MainActivity.inject(Hilt_MainActivity.java:67) 
                 	at ua.dualbot.steammarketbot.Hilt_MainActivity$1.onContextAvailable(Hilt_MainActivity.java:38) 
                 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99) 
                 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:362) 
                 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:217) 
                 	at ua.dualbot.steammarketbot.MainActivity.onCreate(MainActivity.kt:16) 
                 	at android.app.Activity.performCreate(Activity.java:8000) 
                 	at android.app.Activity.performCreate(Activity.java:7984) 
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309) 
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422) 
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
                 	at android.os.Handler.dispatchMessage(Handler.java:106) 
                 	at android.os.Looper.loop(Looper.java:223) 
                 	at android.app.ActivityThread.main(ActivityThread.java:7656) 
                 	at java.lang.reflect.Method.invoke(Native Method) 
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
18:06:44.496  E  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.impl.LogFactoryImpl" on path: DexPathList[[zip file "/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/base.apk"],nativeLibraryDirectories=[/data/app/~~LJkowMeextly5HUySYy5ZA==/ua.dualbot.steammarketbot-dSofr9taUgd64WNXr_84zw==/lib/x86, /system/lib, /system_ext/lib]]
                 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                 	at org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020)
```

**Comment by PolyakovVladislav** [comment]
My god...
`minifyEnabled true`
in my build configuration caused this issue.

**Comment by rbri** [comment]
great thanks for the info - will close this.

Have fun/success using HtmlUnit.
