### ISSUE TITLE
HtmlUnit - Exception invoking drawImage due to awt.Color missing?

### ISSUE THREAD

**Issue by DeborahAnn032** [HtmlUnit/htmlunit-android#27]
I am using HtmlUnit on my android project:

        implementation group: 'org.htmlunit', name: 'htmlunit3-android', version: '3.5.0'

I am simply try to get a webpage:

        private final static String LOGIN_URL = "https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin";
            private final static WebClient webClient = new WebClient(BrowserVersion.FIREFOX);
            java.util.logging.Logger.getLogger("org.apache.http").setLevel(java.util.logging.Level.OFF);
            final HtmlPage page = webClient.getPage(LOGIN_URL);
    

However this is the exception I get at runtime:

    
          Error during JavaScript execution
     ======= EXCEPTION START ========
     Exception class=[java.lang.RuntimeException]
     org.htmlunit.ScriptException: Exception invoking drawImage
     at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:996)
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348)
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620)
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340)
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377)
     at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:171)
     at org.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1504)
     at org.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4)
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348)
     at org.htmlunit.html.DomElement.fireEvent(DomElement.java:1504)
     at org.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:892)
     at org.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
     at org.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
     at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:340)
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:683)
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:565)
     at org.htmlunit.WebClient.getPage(WebClient.java:483)
     at org.htmlunit.WebClient.getPage(WebClient.java:390)
     at org.htmlunit.WebClient.getPage(WebClient.java:528)
     at org.htmlunit.WebClient.getPage(WebClient.java:510)
     at com.port.app.thread.PTCThread.run(PTCThread.java:55)
     Caused by: java.lang.RuntimeException: Exception invoking drawImage
     at org.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:245)
     at org.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:423)
     at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1874)
     at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
     at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
     at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
     at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:334)
     at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3969)
     at org.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:916)
     at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:979)
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590) 
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348) 
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923) 
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895) 
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620) 
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613) 
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340) 
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377) 
     at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:171) 
     at org.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1504) 
     at org.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4) 
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590) 
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348) 
     at org.htmlunit.html.DomElement.fireEvent(DomElement.java:1504) 
     at org.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:892) 
     at org.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319) 
     at org.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165) 
     at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:340) 
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:683) 
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:565) 
     at org.htmlunit.WebClient.getPage(WebClient.java:483) 
     at org.htmlunit.WebClient.getPage(WebClient.java:390) 
     at org.htmlunit.WebClient.getPage(WebClient.java:528) 
     at org.htmlunit.WebClient.getPage(WebClient.java:510) 
     at com.port.app.thread.PTCThread.run(PTCThread.java:55) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
     at org.htmlunit.platform.canvas.rendering.AwtRenderingBackend.<clinit>(AwtRenderingBackend.java:82)
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:454)
     at java.lang.Class.forName(Class.java:379)
     at org.htmlunit.platform.Platform.getRenderingBackend(Platform.java:125)
     at org.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.getRenderingBackend(CanvasRenderingContext2D.java:86)
     at org.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.drawImage(CanvasRenderingContext2D.java:402)
     at java.lang.reflect.Method.invoke(Native Method)
     at org.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:222)
     at org.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:423) 
     at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1874) 
     at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051) 
     at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89) 
     at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392) 
     at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:334) 
     at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3969) 
     at org.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:916) 
     at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:979) 
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590) 
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348) 
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923) 
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895) 
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620) 
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613) 
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340) 
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377) 
     at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:171) 
     at org.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1504) 
     at org.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4) 
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590) 
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348) 
     at org.htmlunit.html.DomElement.fireEvent(DomElement.java:1504) 
     at org.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:892) 
     at org.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319) 
     at org.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165) 
     at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:340) 
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:683) 
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:565) 
     at org.htmlunit.WebClient.getPage(WebClient.java:483) 
     at org.htmlunit.WebClient.getPage(WebClient.java:390) 
     at org.htmlunit.WebClient.getPage(WebClient.java:528) 
     at org.htmlunit.WebClient.getPage(WebClient.java:510) 
     at com.port.app.thread.PTCThread.run(PTCThread.java:55) 
     2023-09-07 12:07:21.876 25293-31854 JavaScriptErrorListener com.example.port.app E Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Color" on path: DexPathList[[dex file "/data/data/com.example.port.app/code_cache/.overlay/base.apk/classes5.dex", dex file "/data/data/com.example.port.app/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~iIkhggH0GXZcrgC-ngqJIA==/com.example.port.app-cXagIADBHqRc9NypwP7SBA==/base.apk"],nativeLibraryDirectories=[/data/app/~~iIkhggH0GXZcrgC-ngqJIA==/com.example.port.app-cXagIADBHqRc9NypwP7SBA==/lib/arm64, /system/lib64]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
     ... 45 more
     Enclosed exception: 
     java.lang.RuntimeException: Exception invoking drawImage
     at org.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:245)
     at org.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:423)
     at org.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1874)
     at org.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1051)
     at org.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
     at org.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
     at org.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:334)
     at org.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3969)
     at org.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:916)
     at org.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:979)
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348)
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:923)
     at org.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:895)
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620)
     at org.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:340)
     at org.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:377)
     at org.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:171)
     at org.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1504)
     at org.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4)
     at org.htmlunit.corejs.javascript.Context.call(Context.java:590)
     at org.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
     at org.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:348)
     at org.htmlunit.html.DomElement.fireEvent(DomElement.java:1504)
     at org.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:892)
     at org.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
     at org.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
     at org.htmlunit.html.HtmlPage.initialize(HtmlPage.java:340)
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:683)
     at org.htmlunit.WebClient.loadWebResponseInto(WebClient.java:565)
     at org.htmlunit.WebClient.getPage(WebClient.java:483)
     at org.htmlunit.WebClient.getPage(WebClient.java:390)
     at org.htmlunit.WebClient.getPage(WebClient.java:528)
     at org.htmlunit.WebClient.getPage(WebClient.java:510)
     at com.port.app.thread.PTCThread.run(PTCThread.java:55)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
     at org.htmlunit.platform.canvas.rendering.AwtRenderingBackend.<clinit>(AwtRenderingBackend.java:82)
     at java.lang.Class.classForName(Native Method)
     at java.lang.Class.forName(Class.java:454)
     2023-09-07 12:07:21.876 25293-31854 JavaScriptErrorListener com.example.port.app E at java.lang.Class.forName(Class.java:379)
     at org.htmlunit.platform.Platform.getRenderingBackend(Platform.java:125)
     at org.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.getRenderingBackend(CanvasRenderingContext2D.java:86)
     at org.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.drawImage(CanvasRenderingContext2D.java:402)
     at java.lang.reflect.Method.invoke(Native Method)
     at org.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:222)
     ... 36 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.Color" on path: DexPathList[[dex file "/data/data/com.example.port.app/code_cache/.overlay/base.apk/classes5.dex", dex file "/data/data/com.example.port.app/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~iIkhggH0GXZcrgC-ngqJIA==/com.example.port.app-cXagIADBHqRc9NypwP7SBA==/base.apk"],nativeLibraryDirectories=[/data/app/~~iIkhggH0GXZcrgC-ngqJIA==/com.example.port.app-cXagIADBHqRc9NypwP7SBA==/lib/arm64, /system/lib64]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
     ... 45 more
     == CALLING JAVASCRIPT ==
     function(){c.drawImage(a,0,0),Modernizr.addTest("todataurljpeg",function(){return b.toDataURL("image/jpeg").indexOf("data:image/jpeg")===0}),Modernizr.addTest("todataurlwebp",function(){return b.toDataURL("image/webp").indexOf("data:image/webp")===0})}
     ======= EXCEPTION END ========

    

The issue seems to be with the drawImage method due to the awt.Color class missing in Android.

I am also getting a few warnings regarding the CSS parser but I don't think are relevant:

        ologin      W  CSS error: 'https://assets.pokemon.com/static2/_ui/css/main.css' [1:199442] Duplicate pseudo class ":hover" or pseudo class ":hover" not at end.
    2023-09-07 12:07:13.894 25293-31854 DefaultCssErrorHandler  com.example.port.appn      W  CSS warning: 'https://assets.pokemon.com/static2/_ui/css/main.css' [1:199442] Ignoring the whole rule.
    2023-09-07 12:07:13.896 25293-31854 DefaultCssErrorHandler  com.example.port.appn      W  CSS error: 'https://assets.pokemon.com/static2/_ui/css/main.css' [1:199628] Duplicate pseudo class ":before" or pseudo class ":before" not at end.
    2023-09-07 12:07:13.896 25293-31854 DefaultCssErrorHandler  com.example.port.appn      W  CSS warning: 'https://assets.pokemon.com/static2/_ui/css/main.css' [1:199628] Ignoring the whole rule.
    2023-09-07 12:07:13.897 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.899 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.906 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.909 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.914 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.915 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)
    2023-09-07 12:07:13.922 25293-31725 rt.app          com.example.port.appn      I  Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)

**Comment by rbri** [comment]
@DeborahAnn032 really strange - can reproduce this here and will try to fix that

**Comment by rbri** [comment]
@DeborahAnn032 
Have fixed the to problems with some platform specific stuff - you can try with 3.6.0-SNAPSHOT.

There is still the problem with the cssparser ( Method exceeds compiler instruction limit: 39878 in int org.htmlunit.cssparser.parser.javacc.CSS3ParserTokenManager.jjMoveNfa_0(int, int)).

I have to think about a solution here....

**Comment by DeborahAnn032** [comment]
Thanks, I will try and let you know!

**Comment by DeborahAnn032** [comment]
`Unknown host 'os1.oss.sonatype.org: nodename nor servname provided, or not known'. You may need to adjust the proxy settings in Gradle.`

It seems it doesn't find the hostname for the snapshots repositories.

**Comment by rbri** [comment]
its https://s01.oss.sonatype.org

**Comment by DeborahAnn032** [comment]
The issue seems to be fixed. As you already said there is still the minor issue with the css parser.

**Comment by rbri** [comment]
Great, but the issue with the CSS parser is in general not a minor one - will require some time and some research to get this done.

**Comment by rbri** [comment]
@DeborahAnn032 will close this as it works for you - the new release will be out soon.
